#- name: play for variables
#  hosts: all
#  vars:
#    URL: play.example.com
#  tasks:
#    - name: Print a value
#      ansible.builtin.debug:
#        msg: URL - {{URL}}
#
#- name: play for variable files
#  hosts: all
#  vars_files:
#    - sample-vars.yml
#  tasks:
#    - name: Print URL
#      ansible.builtin.debug:
#        msg: URL - {{URL}}
#
#- name: play for scope of variables
#  hosts: all
#  tasks:
#    - name: Print URL1
#      ansible.builtin.debug:
#        msg: URL - {{URL}}
#      vars:
#        URL:  task1.example.com
#    - name: Print URL2
#      ansible.builtin.debug:
#        msg: URL - {{URL}}
#      vars:
#        URL: task2.example.com

- name: variable from facts
  hosts: all
  tasks:
    - name: print variable from facts
      ansible.builtin.debug:
        msg: hostname - {{ ansible_fqdn }}

- name: register variables
  hosts: all
  tasks:
    - name: uptime command
      ansible.builtin.shell:  uptime
      register: out

    - name: print uptime output
      ansible.builtin.debug:
        msg: "{{out.stdout}}"
